language: node_js
node_js:
  - v6
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm test -- --coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master

